#!/usr/bin/env bash

# ======================== 全局设定 ==========================

# 自动平衡: 打开窗口自动调整收窗口大小
yabai -m config auto_balance off
# 默认新窗口比例
yabai -m config split_ratio 0.50
# 设置布局模式: bsp(自动平铺) | float | stack(层叠)
yabai -m config layout stack
# 新窗口位置: first_child | second_child(右下方)
yabai -m config window_placement second_child
# 窗口间距
yabai -m config window_gap 10
# 窗口shadow: on | off | float
yabai -m config window_shadow off


###############################################################################
#                          Custom padding settings
###############################################################################

if command -v sketchybar &>/dev/null; then
  display_resolution=$(system_profiler SPDisplaysDataType | grep Resolution)

  yabai -m config top_padding 48
  yabai -m config bottom_padding 8
  yabai -m config left_padding 8
  yabai -m config right_padding 8
fi

###############################################################################
#                               Transparency
###############################################################################

yabai -m config window_opacity off

opacity_value=0.9

###############################################################################
#                             sub-layer=normal
###############################################################################

# https://github.com/koekeishiya/yabai/issues/1929
yabai -m rule --add app=".*" sub-layer=normal

###############################################################################
#                              Signal events
###############################################################################

###############################################################################
#                                Defaults
###############################################################################


###############################################################################
#                             Yabai Spaces
###############################################################################


yabai -m space 1 --label desk1
yabai -m space 2 --label desk2 --layout bsp
yabai -m space 3 --label desk3 
yabai -m space 4 --label desk4
yabai -m space 5 --label desk5 
yabai -m space 6 --label desk6
yabai -m space 7 --label desk7
yabai -m space 8 --label desk8
yabai -m space 9 --label desk9
yabai -m space 10 --label desk10

displays_json="$(yabai -m query --displays)"
display_count="$(echo "$displays_json" | jq 'length')"


if [ "$display_count" -eq 1 ]; then
  yabai -m space 1 --label Main
  yabai -m space 2 --label Main-Term --layout bsp
  yabai -m space 3 --label Main-Xcode --layout bsp
elif [ "$display_count" -eq 3 ]; then
  main_display_id="$(
    echo "$displays_json" |
      jq 'max_by(.spaces | length) | .id'
  )"

  main_display_spaces="$(
    echo "$displays_json" |
      jq --argjson main_display_id "$main_display_id" '
        map(select(.id == $main_display_id))[0].spaces
      '
    )"

  left_display_spaces="$(
    echo "$displays_json" |
      jq --argjson main_display_id "$main_display_id" '
        map(select(.id != $main_display_id))
        | sort_by(.frame.x)
        | .[0].spaces
      '
  )"
  right_display_spaces="$(
    echo "$displays_json" |
      jq --argjson main_display_id "$main_display_id" '
        map(select(.id != $main_display_id))
        | sort_by(.frame.x)
        | .[1].spaces
      '
    )"

    main1="$(echo "$main_display_spaces" | jq '.[0]')"
    main2="$(echo "$main_display_spaces" | jq '.[1]')"
    main3="$(echo "$main_display_spaces" | jq '.[2]')"
    main4="$(echo "$main_display_spaces" | jq '.[3]')"

    left1="$(echo "$left_display_spaces" | jq '.[0]')"
    left2="$(echo "$left_display_spaces" | jq '.[1]')"

    right1="$(echo "$right_display_spaces" | jq '.[0]')"
    right2="$(echo "$right_display_spaces" | jq '.[1]')"

    # 中间27寸主屏
    yabai -m space "$main1" --label Main
    yabai -m space "$main2" --label Main-Term --layout bsp
    yabai -m space "$main3" --label Main-Xcode --layout float
    yabai -m space "$main4" --label Main-Dotfiles --layout bsp

    # 左边Macbook
    yabai -m space "$left1" --label Left
    yabai -m space "$left2" --label Left-Chat --layout float

    # 右边竖屏
    yabai -m space "$right1" --label Right --layout bsp
    yabai -m space "$right2" --label Right2

    # Macbook padding
    yabai -m config --space "$left1" top_padding 18
    yabai -m config --space "$left2" top_padding 18
fi

# ======================== 应用规则(Window Rules) ==========================

apps_mgoff="(Calculator|Notes|Finder|Xnapper)"

# 黑名单
yabai -m rule --add app="^${apps_mgoff}$" manage=off 

yabai -m rule --add app="^Ghostty$" space="Main-Term"
yabai -m rule --add app="^kitty$" space="Main-Dotfiles"
yabai -m rule --add app="^Xcode$" space="Main-Xcode"
yabai -m rule --add app="^Simulator$" space="Main-Xcode"


# 左边工具
yabai -m rule --add app="^ChatGPT$" space="Left"
yabai -m rule --add app="^WeChat$" space="Left-Chat"
yabai -m rule --add app="^Stickies$" space="Left-Chat"
yabai -m rule --add app="^QQ$" space="Left-Chat"

# 右边竖屏
yabai -m rule --add app="^Google Chrome$" space="Right"
yabai -m rule --add app="^Safari$" space="Right"

yabai -m rule --apply
