# action key
unbind C-b
set-option -g prefix C-t

set -g mouse on

# Display lazygit
bind -r g display-popup -d '#{pane_current_path}' -w80% -h80% -E lazygit


# Plugins
set -g @plugin 'tmux-plugins/tpm'
# Install Plugins
set -g @plugin 'tmux-plugins/tmux-sensible' # Default
set -g @plugin 'tmux-plugins/tmux-resurrect' # persist tmux sessions after computer restart
set -g @plugin 'tmux-plugins/tmux-continuum' # automatically saves sessions for you every 15 minutes

source ~/ghq/github.com/folke/tokyonight.nvim/extras/tmux/tokyonight_day.tmux

# Initialize TMUX plugin manager
run '~/.tmux/plugins/tpm/tpm'
