# [GENERAL]
import = ["~/.config/alacritty/themes/themes/solarized_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
padding = { x = 3, y = 3 }
opacity = 0.8
blur = true
position = { x = 100, y = 120 }
dimensions = { lines = 56, columns = 180 }
resize_increments = true

[font]
size = 14
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Regular"
# bold.family = "JetBrainsMono Nerd Font"
# bold.style = "Bold"
# italic.family = ""
# italic.style = ""
# bold_italic.family = ""
# bold_italic.style = ""


[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true
