#!/usr/bin/env bash
#

info () {
  printf "\r [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K [ \033[00;32mOK\033[0m ] $1\n"
}


setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink]
  then
    info 'setup gitconfig'

    user ' - Wath is your github author name?'
    read -e git_authorname
    user ' - Wath is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" \
        -e "s/AUTHOREMAIL/$git_authoremail/g" \
        -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" \
        git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    success 'gitconfig'

  fi
}

setup_gitconfig

echo ''
echo ' All instaled!'
