# Fonts
font_family      JetBrains Mono
font_size 14

# 滚动历史
scrollback_lines 10000

# 关闭窗口不再二次确认
confirm_os_window_close 0

# 光标
cursor_shape beam
cursor_blink_interval 0

# Tab 行为
tab_bar_edge top
tab_bar_style powerline
tab_bar_template "{index}: {title}"

# Color scheme
background_opacity 0.96
background_blur 10
hide_window_decorations titlebar-only

# Tab 切换
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9


# BEGIN_KITTY_THEME
# Tokyo Night Day
include current-theme.conf
# END_KITTY_THEME
